name: 'python-pytest'
description: 'Run pytest command'
author: 'xoviat'
branding:
  icon: play-circle
  color: black
inputs:
  args:
    description: Arguments for the pytest command
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
